<?php
include("pages/header.php");
include("pages/section.php");
include("pages/about.php");
//include("pages/whyUs.php");
include("pages/menu.php");
include("pages/gallery.php");
//include("pages/specials.php");
//include("pages/events.php");
//include("pages/booking.php");
include("pages/testimonials.php");
include("pages/chefs.php");
include("pages/contact.php");
include("pages/footer.php");
?>